name: Deploy the code coming from Pull Request (before PR merge) as Knative serving

on:
  pull_request:
    branches:
    - main
env:
  ENV: "dev"
  QUAY_DOCKER_USERNAME: ${{ secrets.QUAY_DOCKER_USERNAME }}
  QUAY_DOCKER_PASSWORD: ${{ secrets.QUAY_DOCKER_PASSWORD }}
  QUAY_PULL_SECRET: ${{ secrets.QUAY_DOCKER_CONFIIG_JSON_PULL_SECRET}}
  QUAY_CONTAINER_REGISTRY: ${{ secrets.QUAY_CONTAINER_REGISTRY}} # use "docker.io" for docker hub 
  OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_DEV_SERVER_URL}}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_DEV_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_DEV_NAMESPACE }}

jobs:
  pull_request_workflow:
    name: Deploy the code coming from Pull Request (before PR merge)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build container image
        run: docker build -t ${{ env.QUAY_CONTAINER_REGISTRY }}/${{ env.QUAY_DOCKER_USERNAME }}/racing-game-app-openshift:$(echo $GITHUB_SHA | head -c7) .

      - name: Docker Login
        run: docker login -u ${{ env.QUAY_DOCKER_USERNAME }} -p ${{ env.QUAY_DOCKER_PASSWORD }} ${{ env.QUAY_CONTAINER_REGISTRY }}

      - name: Push image to Quay
        run: docker push ${{ env.QUAY_CONTAINER_REGISTRY }}/${{ env.QUAY_DOCKER_USERNAME }}/racing-game-app-openshift:$(echo $GITHUB_SHA | head -c7)

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

#      - name: registry
#        run: echo ${{ env.QUAY_CONTAINER_REGISTRY }}

#      - name: username
#        run: echo ${{ env.QUAY_DOCKER_USERNAME }}


      - name: Setting Container Image Name
#        env: 
#          CONTAINER_IMAGE_NAME: ${{ env.QUAY_CONTAINER_REGISTRY }}/${{ env.QUAY_DOCKER_USERNAME }}/racing-game-app-openshift:$(echo $GITHUB_SHA | head -c7)        
        run: echo "CONTAINER_IMAGE_NAME=${{ env.QUAY_CONTAINER_REGISTRY }}/${{ env.QUAY_DOCKER_USERNAME }}/racing-game-app-openshift:$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: test
        run: echo $CONTAINER_IMAGE_NAME

      - name: Create Knative Service
        id: kn_service_deploy
        uses: redhat-actions/kn-service-manager@v1
#        env: 
#          CONTAINER_IMAGE_NAME: ${{ env.QUAY_CONTAINER_REGISTRY }}/${{ env.QUAY_DOCKER_USERNAME }}/racing-game-app-openshift:$(echo $GITHUB_SHA | head -c7)
        with:
          service_name: racing-game-app-openshif-knative
          force_create: true
#          container_image: ${{ env.CONTAINER_IMAGE_NAME }}
          container_image: "quay.io/karasing/racing-game-app-openshift"

      - name: Show Kn Service URL
        run: echo ${{ steps.kn_service_deploy.outputs.service_url }}
        id: openshift_route_name

      - name: Add a comment to PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Code has been deployed on OpenShift , here is the link to application endpoint http://${{ steps.openshift_route_name.outputs.route_name}}
          reactions: rocket